### ISSUE TITLE
Add Clover Health

### ISSUE THREAD

**Issue by saraatclover** [doubleunion/opendiversitydata#107]
Add a health.yml and include Clover Health's information there:

```
companies:
  - name: Clover Health
    url: http://www.cloverhealth.com
    twitter: Clover_Health
    img: clover-health.png
    diversitydata: Yes
    eeo-1: Yes
    documentation: https://technology.cloverhealth.com/clover-healths-first-diversity-data-report-942f82648993
    date-updated: 2017
    status: Yes
```

Our icon is attached.

![clover-health](https://user-images.githubusercontent.com/11307674/28849792-a3dc7956-76cd-11e7-8d18-3bb588e5f4cf.png)
